-- adicionando Condomínio ao BD
INSERT INTO CONDOMINIOS(
	ID_CONDOMINIO,
	QTD_BLOCOS_CONDOMINIO,
	VAL_TOTAL_MENSAL
) VALUES (
	"ALPHA",
	4,
	4200.00
);


-- adicionando Bloco ao DB (com FK)
INSERT INTO BLOCOS(
	ID_BLOCO,
	QTD_PREDIOS_BLOCO,
	COD_CONDOMINIO
) VALUES (
	"BLOCO 1 - ALPHA",
	4,
	4
);

-- adicionando Prédio ao DB (com FK)
INSERT INTO PREDIOS(
	ID_PREDIO,
	QTD_APARTAMENTOS_PREDIO,
	VAL_MENSALIDADES_PREDIO,
	VAL_FRACAO_IDEAL_PREDIO,
	COD_BLOCO
) VALUES (
	"PREDIO A - ALPHA",
	16,
	550.00,
	1220.00,
	1
);

-- adicionando Morador ao DB (com FK)
INSERT INTO MORADORES(
	NOME_MORADOR,
	RG_MORADOR,
	CPF_MORADOR,
	DAT_NASCIMENTO_MORADOR,
	COD_PREDIO
) VALUES (
	"VINÍCIUS DE SOUZA",
	"0564865588",
	"47987458805",
	"19980722",
	1
);
