SELECT current_timestamp;

INSERT INTO MORADOR(
	NOME_MORADOR
   ,RG_MORADOR
   ,DAT_NASCIMENTO_MORADOR
   ,ULTIMA_MODIFICACAO
) VALUES (
    'Roberson'
   ,'1112225550'
   ,'19901115'
   ,'2017-05-23 21:36:42'
);

INSERT INTO MORADOR_CPF(
    COD_MORADOR
   ,CPF_MORADOR
) VALUES (
    (SELECT COD_MORADOR FROM MORADOR WHERE NOME_MORADOR = 'Roberson' AND ULTIMA_MODIFICACAO = '2017-05-23 21:36:42')
   ,'10011101010'
);

-- 
SELECT NOME_MORADOR FROM MORADOR WA WHERE WA.COD_MORADOR = (SELECT CPF.COD_MORADOR FROM MORADOR_CPF CPF WHERE CPF.CPF_MORADOR = '10011101010');
SELECT NOME_MORADOR 'NOME', RG_MORADOR 'RG', COALESCE (MCPF.CPF_MORADOR, 'NÃO POSSUI') 'CPF' , COALESCE(MCNPJ.CNPJ_MORADOR, 'NÃO POSSUI') 'CNPJ', DAT_NASCIMENTO_MORADOR 'DATA DE NASCIMENTO', ULTIMA_MODIFICACAO 'ULTIMA MODIFICAÇÃO' FROM MORADOR MOR LEFT JOIN MORADOR_CPF MCPF ON MCPF.COD_MORADOR = MOR.COD_MORADOR LEFT JOIN MORADOR_CNPJ MCNPJ ON MCNPJ.COD_MORADOR = MOR.COD_MORADOR;