CREATE SCHEMA CONFLOW;
USE CONFLOW;


--

CREATE TABLE MORADORES(
	COD_MORADOR					INT	NOT NULL		AUTO_INCREMENT,
	NOME_MORADOR				VARCHAR(80)		NOT NULL,
	RG_MORADOR					VARCHAR(10),
	CPF_MORADOR					VARCHAR(14)		NOT NULL,
	DAT_NASCIMENTO_MORADOR	DATE,
	
	PRIMARY KEY (COD_MORADOR)
	
);

CREATE TABLE BOLETOS(
	COD_BOLETO					INT		NOT NULL		AUTO_INCREMENT,
	VAL_BOLETO					FLOAT		NOT NULL,
	VAL_MULTA_BOLETO			FLOAT		DEFAULT 0.00,
	DAT_EXPEDICAO_BOLETO			DATE		NOT NULL,
	DAT_VENCIMENTO_BOLETO			DATE		NOT NULL,
	
	COD_MORADOR					INT	NOT NULL,
	
	PRIMARY KEY (COD_BOLETO),
	FOREIGN KEY (COD_MORADOR)
		REFERENCES MORADORES(COD_MORADOR)
	
);

-- 

CREATE TABLE CONDOMINIOS(
	COD_CONDOMINIO					INT				NOT NULL		AUTO_INCREMENT,
	ID_CONDOMINIO					VARCHAR(80),
	QTD_BLOCOS_CONDOMINIO		INT				NOT NULL		DEFAULT 1,
	QTD_PREDIOS_CONDOMINIO		INT				NOT NULL		DEFAULT 1,
	VAL_TOTAL_MENSAL				FLOAT				DEFAULT 0.00,
	
	COD_BLOCOS						VARCHAR(255),
	
	PRIMARY KEY (COD_CONDOMINIO)
	
);

CREATE TABLE BLOCOS(
	COD_BLOCO					INT				NOT NULL			AUTO_INCREMENT,
	ID_BLOCO						VARCHAR(80),
	QTD_PREDIOS_BLOCO			INT				NOT NULL,
	
	COD_CONDOMINIO				INT	NOT NULL,
	
	PRIMARY KEY (COD_BLOCO),
	FOREIGN KEY (COD_CONDOMINIO)
		REFERENCES CONDOMINIOS(COD_CONDOMINIO)
	
);

CREATE TABLE PREDIOS(
	COD_PREDIO						INT				NOT NULL			AUTO_INCREMENT,
	ID_PREDIO						VARCHAR(80),
	QTD_APARTAMENTOS_PREDIO		INT				NOT NULL,
	VAL_MENSALIDADES_PREDIO		FLOAT				NOT NULL,
	VAL_FRACAO_IDEAL_PREDIO		FLOAT,
	
	COD_BLOCO					INT	NOT NULL,
	
	PRIMARY KEY (COD_PREDIO),
	FOREIGN KEY (COD_BLOCO)
		REFERENCES BLOCOS(COD_BLOCO)
	
);

CREATE TABLE APARTAMENTOS(
	COD_APARTAMENTO				INT				NOT NULL			AUTO_INCREMENT,

	COD_BOLETOS_A_PAGAR			VARCHAR(500),
	DON_APARTAMENTO				INT,
	
	PRIMARY KEY (COD_APARTAMENTO),
	FOREIGN KEY (DON_APARTAMENTO)
		REFERENCES MORADORES (COD_MORADOR)
	
);

CREATE TABLE ESTACIONAMENTO(
	COD_ESTACIONAMENTO				INT	 			NOT NULL		AUTO_INCREMENT,
	ID_ESTACIONAMENTO					INT				NOT NULL,
	
	COD_DONO						INT	NOT NULL,
	
	PRIMARY KEY (COD_ESTACIONAMENTO),
	FOREIGN KEY (COD_DONO)
		REFERENCES MORADORES(COD_MORADOR)
	
);
