
WITH INS_CPF ( NOME_MORADOR, DAT_NASCIMENTO_MORADOR, RG_MORADOR, CPF_MORADOR ) AS
( VALUES
	( 'Vinícius de Souza', '19980722', '1000200001', '10000200001' )
)
INSERT INTO MORADORES ( NOME_MORADOR, DAT_NASCIMENTO_MORADOR, RG_MORADOR ) VALUES ( INS_CPF.NOME_MORADOR, INS_CPF.DAT_NASCIMENTO_MORADOR, INS_CPF.RG_MORADOR )
INSERT INTO MORADORES_CPF (MORADOR_ID, CPF_MORADOR)
SELECT
		MORADORES.COD_MORADOR, INS_CPF.CPF_MORADOR
FROM
	MORADORES;
