-- Check current date and time
SELECT CURRENT_TIMESTAMP; 

-- Code to add a new 'Morador' row
INSERT INTO MORADOR (
	NOME_MORADOR,
	RG_MORADOR,
	DAT_NASCIMENTO_MORADOR,
	ULTIMA_MODIFICACAO
) VALUES (
	'Vinícius de Souza',
	'1000200019',
	'19980722',
	'2017-05-24 13:39:28'
);

-- Code to add a new 'Morador_CPF' row
INSERT INTO MORADOR_CPF(
	COD_MORADOR,
	CPF_MORADOR
) VALUES (
	(SELECT COD_MORADOR FROM MORADOR WHERE NOME_MORADOR = 'Vinícius de Souza' AND ULTIMA_MODIFICACAO = '2017-05-24 13:39:28'),
	'10002200199'
);


-- Code to list all 'Morador' rows plus 'CPF' and 'CNPJ' formated neatly.
SELECT    MOR.COD_MORADOR 'Código ID',
          MOR.NOME_MORADOR 'Nome',
          MOR.RG_MORADOR 'RG',
COALESCE (CPF.CPF_MORADOR, 'Não possui') 'CPF',
COALESCE (CNPJ.CNPJ_MORADOR, 'Não possui') 'CNPJ', MOR.DAT_NASCIMENTO_MORADOR 'Data de Nascimento'
FROM MORADOR MOR
LEFT JOIN MORADOR_CPF CPF ON CPF.COD_MORADOR = MOR.COD_MORADOR
LEFT JOIN MORADOR_CNPJ CNPJ ON CNPJ.COD_MORADOR = MOR.COD_MORADOR;
